#!/usr/bin/env bash
# Part F verification: apply every manifest, wait for the training Job, roll out
# the serving Deployment, port-forward the Service and hit /predict. Output is
# teed into docs/evidence/k8s.md for the final PR description.
#
#   bash scripts/verify_k8s.sh
#
# Prerequisites: a running cluster (Docker Desktop Kubernetes, minikube or kind)
# with mlops-train:v1 and mlops-serve:v1 available to it. See README.md.
set -euo pipefail

cd "$(dirname "$0")/.."

NAMESPACE="${NAMESPACE:-ml-training}"
EVIDENCE="${EVIDENCE:-docs/evidence/k8s.md}"
JOB_TIMEOUT="${JOB_TIMEOUT:-30m}"
PORT="${PORT:-8080}"

mkdir -p "$(dirname "$EVIDENCE")"
: >"$EVIDENCE"
say()  { printf '%s\n' "$*" | tee -a "$EVIDENCE"; }
step() { say ""; say "### \$ $*"; say '```'; ( "$@" 2>&1 || true ) | tee -a "$EVIDENCE"; say '```'; }

cleanup() { [[ -n "${FORWARD_PID:-}" ]] && kill "$FORWARD_PID" 2>/dev/null || true; }
trap cleanup EXIT

say "# Part F - end-to-end validation on Kubernetes"
say ""
say "Generated by \`scripts/verify_k8s.sh\` on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"

step kubectl config current-context
step kubectl get nodes -o wide

# ------------------------------------------------------- 1. training ---------
say ""; say "## 1. Namespace, ConfigMaps and the training Job"
step kubectl apply -f k8s/namespace.yaml
step kubectl apply -f k8s/configmap.yaml
step kubectl apply -f k8s/training-job.yaml
step kubectl get pvc -n "$NAMESPACE"

say ""; say "Waiting up to $JOB_TIMEOUT for the Job to complete..."
step kubectl wait --for=condition=complete "job/pytorch-training" -n "$NAMESPACE" --timeout="$JOB_TIMEOUT"
step kubectl get job pytorch-training -n "$NAMESPACE" -o wide
step kubectl logs "job/pytorch-training" -n "$NAMESPACE" --tail=40

# -------------------------------------------------------- 2. serving ---------
say ""; say "## 2. Serving Deployment, Service and HPA"
step kubectl apply -f k8s/serving-deployment.yaml
step kubectl apply -f k8s/serving-service.yaml
step kubectl apply -f k8s/hpa.yaml
step kubectl rollout status deployment/model-serving -n "$NAMESPACE" --timeout=5m

# ------------------------------------------------------- 3. healthy ----------
say ""; say "## 3. Pods are running and healthy"
step kubectl get pods,svc,hpa -n "$NAMESPACE" -o wide
step kubectl describe deployment model-serving -n "$NAMESPACE"
step kubectl logs -l app=model-serving -n "$NAMESPACE" --tail=8 --prefix

# ------------------------------------------------------- 4. predict ----------
say ""; say "## 4. Prediction through the Service"
kubectl port-forward "svc/model-serving" "${PORT}:80" -n "$NAMESPACE" >/tmp/port-forward.log 2>&1 &
FORWARD_PID=$!
say ""; say "\`kubectl port-forward svc/model-serving ${PORT}:80 -n ${NAMESPACE}\` (pid $FORWARD_PID)"
for _ in $(seq 1 20); do
  curl -fsS "http://localhost:${PORT}/health" >/dev/null 2>&1 && break
  sleep 2
done

[[ -f test_image.png ]] || python3 scripts/make_test_image.py >/dev/null 2>&1 || \
  python3 -c "from PIL import Image; Image.new('RGB',(32,32),(64,128,192)).save('test_image.png')"

step curl -sS "http://localhost:${PORT}/health"
step curl -sS -X POST "http://localhost:${PORT}/predict" -F "image=@test_image.png"

# --------------------------------------------- 5. rolling update -------------
say ""; say "## 5. Rolling update keeps the Service available (maxUnavailable: 0)"
step kubectl rollout restart deployment/model-serving -n "$NAMESPACE"
step kubectl rollout status deployment/model-serving -n "$NAMESPACE" --timeout=5m
step curl -sS -X POST "http://localhost:${PORT}/predict" -F "image=@test_image.png"

echo
echo "Evidence written to $EVIDENCE"
