#!/usr/bin/env bash
# Part C verification: build both images, run a short training job, serve the
# checkpoint, hit /health and /predict. Every command and its output is teed
# into docs/evidence/docker.md for the PR description.
#
#   bash scripts/verify_docker.sh            # ~1-2 min training smoke run
#   FULL=1 bash scripts/verify_docker.sh     # full 10-epoch run (slow on CPU)
set -euo pipefail

cd "$(dirname "$0")/.."
REPO="$(pwd)"

IMAGE_TRAIN="${IMAGE_TRAIN:-mlops-train:v1}"
IMAGE_SERVE="${IMAGE_SERVE:-mlops-serve:v1}"
EVIDENCE="${EVIDENCE:-docs/evidence/docker.md}"
BUILD_ARGS=()
[[ -n "${TORCH_INDEX_URL:-}" ]] && BUILD_ARGS+=(--build-arg "TORCH_INDEX_URL=${TORCH_INDEX_URL}")

mkdir -p data checkpoints "$(dirname "$EVIDENCE")"

: >"$EVIDENCE"
say()  { printf '%s\n' "$*" | tee -a "$EVIDENCE"; }
step() { say ""; say "### \$ $*"; say '```'; ( "$@" 2>&1 || true ) | tee -a "$EVIDENCE"; say '```'; }

say "# Part C - local Docker verification"
say ""
say "Generated by \`scripts/verify_docker.sh\` on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
step docker version --format '{{.Server.Version}}'

# ---------------------------------------------------------------- build ------
step docker build -f docker/Dockerfile.train -t "$IMAGE_TRAIN" "${BUILD_ARGS[@]+"${BUILD_ARGS[@]}"}" .
step docker build -f docker/Dockerfile.serve -t "$IMAGE_SERVE" "${BUILD_ARGS[@]+"${BUILD_ARGS[@]}"}" .
step docker images "mlops-train" "mlops-serve"

# --------------------------------------------------------------- training ----
if [[ "${FULL:-0}" == "1" ]]; then
  TRAIN_ENV=()
  say ""; say "_Full run: 10 epochs from configs/training_config.yaml._"
else
  TRAIN_ENV=(-e TRAIN_EPOCHS=2 -e TRAIN_MAX_TRAIN_BATCHES=60 -e TRAIN_MAX_VAL_BATCHES=20
             -e TRAIN_ARCHITECTURE=simple_cnn)
  say ""; say "_Smoke run: TRAIN_* env overrides truncate the epochs (set FULL=1 for the real run)._"

  # Never clobber a real checkpoint - e.g. one trained natively on the Apple
  # silicon GPU, which the container cannot use (no Metal passthrough).
  if [[ -f checkpoints/classifier_v1.pt ]]; then
    TRAIN_ENV+=(-e MODEL_NAME=smoke_v1.pt)
    say "_An existing \`checkpoints/classifier_v1.pt\` was found, so this run writes"
    say "\`smoke_v1.pt\` instead and serving keeps using the better model._"
  fi
fi

step docker run --rm \
  -v "$REPO/data:/app/data" \
  -v "$REPO/checkpoints:/app/checkpoints" \
  "${TRAIN_ENV[@]+"${TRAIN_ENV[@]}"}" \
  "$IMAGE_TRAIN"

step ls -lh checkpoints

# ---------------------------------------------------------------- serving ----
docker rm -f mlops-serve-verify >/dev/null 2>&1 || true
step docker run -d --name mlops-serve-verify -p 8080:8080 \
  -v "$REPO/checkpoints:/app/checkpoints" \
  "$IMAGE_SERVE"

say ""; say "Waiting for the container HEALTHCHECK to report healthy..."
for _ in $(seq 1 40); do
  status="$(docker inspect -f '{{.State.Health.Status}}' mlops-serve-verify 2>/dev/null || echo starting)"
  [[ "$status" == "healthy" ]] && break
  sleep 3
done
step docker inspect -f 'health={{.State.Health.Status}} user={{.Config.User}} exposed={{.Config.ExposedPorts}}' mlops-serve-verify

step curl -sS http://localhost:8080/health

python3 scripts/make_test_image.py >/dev/null 2>&1 || true
[[ -f test_image.png ]] || python3 -c \
  "from PIL import Image; Image.new('RGB',(32,32),(64,128,192)).save('test_image.png')"

step curl -sS -X POST http://localhost:8080/predict -F "image=@test_image.png"
step docker logs --tail 15 mlops-serve-verify

docker rm -f mlops-serve-verify >/dev/null 2>&1 || true
say ""; say "_Serving container stopped and removed._"

echo
echo "Evidence written to $EVIDENCE"
